### ISSUE TITLE
Issues due to gcc submodule in the gdc repo

### ISSUE THREAD

**Issue by TheGag96** [JinShil/arm-none-eabi-gdc#2]
I tried running this script today, and I'm running into issues when the script tries to do `./setup-gcc.sh gcc`. The issue is that the current [GDC repo](https://github.com/D-Programming-GDC/gdc) doesn't contain the gcc submodule that was supposed to be cloned a few lines above. According to the closed GDC PRs, Iain had been setting up the submodule and merging it somewhere, but he deleted whatever branch he was doing it on... Would a solution to just copy the latest gcc files into the folder it expects and be done with it?

**Comment by JinShil** [comment]
A lot has happened with GDC since I last tested this script.  GDC is now an official part of GCC.  So instead of having a GCC submodule and then adding the D programming language to GCC via the `setup-gcc.sh` script, you just need to download GCC.

But it gets more complicated.  GCC needs to be able to build GCC.  The general rule is GCC 8 must be able to build GCC 9, and GCC 9 must be able to build GCC 10, etc..  So, since the latest GDC frontend is programmed in D, and GCC didn't contain D prior to GCC 9, GCC 9 contains an older D frontend written in C++, v2.067 (if I remember correctly).  The latest D compiler, which is written in D, will be added to GCC 10.

So you need to first build a native GCC 9 with the D language enabled to serve as a bootstrap compiler (See https://github.com/JinShil/native-gdc).  Then you can use that to build the latest arm-none-eabi-gcc with the latest D frontend here (https://github.com/D-Programming-GDC/gcc).

I'm sorry I don't have all this scripted.  I'm waiting for GCC 10 to arrive so, hopefully, we won't have to do all of this dancing around.

**Comment by TheGag96** [comment]
Thank you for the quick response! I did already build native-gdc before trying this, so I'll go ahead and see if copying gcc's source into my folder will do the trick. (I'm hoping to use this with devkitARM - I'd be very excited to get BetterC D code running on the 3DS!) If I can't get it to work, I guess I'll just be patient for GDC 10.

**Comment by TheGag96** [comment]
Hm. I tried doing this a couple different ways, and some of the patches always fail to apply (when I looked at the files they were going to change, they seemed to already have the content they were about to apply?), and when make runs, I get `GDC: command not found` as the error. It seems many files have `@GDC@` in them, which it clearly doesn't like... 

(Do you have a built arm-none-eabi-gdc? I'd be willing to use that if you're willing to upload it somewhere haha)

**Comment by JinShil** [comment]
I just updated the script.  It works for me.  Here's what I do.

1. Build [native-gdc](https://github.com/JinShil/native-gdc)
2. Do `export PATH=path-to-native-gdc-bin:$PATH`
3. Run `arm-none-eabi-gdc.sh`

Please give it a try.

**Comment by TheGag96** [comment]
Ah thank you for taking the time to do that, it compiles now! (I'm having trouble getting this to work with devkitARM, but one step further, I suppose...)

**Comment by JinShil** [comment]
Glad that got you further.  You're welcome to ask questions at https://forum.dlang.org/group/gdc if you have trouble getting your code to work.  I'm going to close this issue, as I think building the compiler has been solved.
